//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refuellings
    {
        public int ID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> MarkID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Litter { get; set; }
        public Nullable<System.DateTime> RefuellingDate { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual MarksOfGasoline MarksOfGasoline { get; set; }
        public virtual Users Users { get; set; }
    }
}
